language: cpp
compiler:
  - gcc
  # - clang
os:
  - linux
  - osx

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # Get Clang 3.4
  - if [ "$CXX" == "clang++" ]; then wget https://github.com/Viq111/travis-container-packets/releases/download/clang%2Blibcxx-3.4.2/clang_libcxx.tar.bz2; fi
  - if [ "$CXX" == "clang++" ]; then tar -xjf clang_libcxx.tar.bz2; fi
  - if [ "$CXX" == "clang++" ]; then rm clang_libcxx.tar.bz2 && mv clang_libcxx clang; fi
  - if [ "$CXX" == "clang++" ]; then export PATH=$(pwd)/clang/bin:$PATH; fi
  - if [ "$CXX" == "clang++" ]; then export LIBRARY_PATH=$(pwd)/clang/lib:$LIBRARY_PATH; fi
  - if [ "$CXX" == "clang++" ]; then export LD_LIBRARY_PATH=$(pwd)/clang/lib:$LD_LIBRARY_PATH; fi
  - if [ "$CXX" == "clang++" ]; then export CPLUS_INCLUDE_PATH=$(pwd)/clang/include/c++/v1:$CPLUS_INCLUDE_PATH; fi
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-stdlib=libc++"; fi

  - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # Get boost
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - export BOOST_ROOT=$(pwd)/boost

  # Get CMake 3.1
  - wget https://github.com/Viq111/travis-container-packets/releases/download/cmake-3.1.2/cmake.tar.bz2
  - tar -xjf cmake.tar.bz2
  - rm cmake.tar.bz2
  - export PATH=$(pwd)/cmake/bin:$PATH

  #thrift
  - sudo apt-get update -qq
  - sudo apt-get install libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - wget http://mirror.netcologne.de/apache.org/thrift/0.9.2/thrift-0.9.2.tar.gz
  - tar xfz thrift-0.9.2.tar.gz
  # --with-boost=$(pwd)/../boost/include --with-boost-libdir=$(pwd)/../boost/lib 
  - cd thrift-0.9.2 && ./configure --with-c_glib=no --with-java=no --with-python=no --with-ruby=no --with-erlang=no --with-go=no --with-nodejs=no --with-cpp=yes && sudo make install

script:
  - mkdir -p build || exit $?
  - cd build || exit $?
  - cmake .. || exit $?
  - make all || exit $?
  # - ./test_all || exit $?
  - cd .. || exit $?
